version: '3.9'
name: 'chat'
services:
  postgres:
    container_name: chat
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'